# Generated by Django 3.1.6 on 2021-02-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificationddate',
            new_name='notificationdate',
        ),
    ]
