# Generated by Django 3.1.6 on 2021-02-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0002_jobseeker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='regtdate',
            new_name='regdate',
        ),
    ]
